# Generated by Django 3.2.13 on 2022-11-23 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('released_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_avg', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('genres_info', models.JSONField()),
                ('actor', models.JSONField()),
                ('director', models.JSONField()),
                ('trailer', models.JSONField()),
                ('watch', models.JSONField()),
                ('similar', models.JSONField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('img', models.IntegerField()),
                ('followings', models.ManyToManyField(related_name='followers', to='movies.Profile')),
                ('like_movies', models.ManyToManyField(related_name='like_profiles', to='movies.Movie')),
                ('movie1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie1', to='movies.movie')),
                ('movie10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie10', to='movies.movie')),
                ('movie2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie2', to='movies.movie')),
                ('movie3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie3', to='movies.movie')),
                ('movie4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie4', to='movies.movie')),
                ('movie5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie5', to='movies.movie')),
                ('movie6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie6', to='movies.movie')),
                ('movie7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie7', to='movies.movie')),
                ('movie8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie8', to='movies.movie')),
                ('movie9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie9', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_movies', models.ManyToManyField(related_name='wish_profiles', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_send', to='movies.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recive', to='movies.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.profile')),
            ],
        ),
    ]
